django_websocket_chatting/accounts/urls.py
from django.urls import path
from accounts import views


app_name = "accounts"

urlpatterns = [
    # user
    path('signup/', views.signup, name='signup'),
    path("login/", views.user_login, name="login"),
    path('logout/', views.logout_view, name='logout'),
    path("profile/", views.profile, name="profile"),
    
    # friend url
    path('friend-request/send/', views.SendFriendRequestView.as_view(), name='send-friend-request'),
    path('friend-request/accept/<int:pk>/', views.AcceptFriendRequestView.as_view(), name='accept-friend-request'),
    path('friend-request/reject/<int:pk>/', views.RejectFriendRequestView.as_view(), name='reject-friend-request'),
    
    path('friends/', views.ListFriendsView.as_view(), name='list_friends'),
    path('friend-management/', views.friend_management, name='friend_management'),
    path('friend-profile/', views.friend_profile, name='friend_profile'),   # Friend profile
    path('get-friends-list/', views.get_friends_list, name='get_friends_list'), # return Friend list
    path('friend-requests/received/', views.get_received_friend_requests, name='get_received_friend_requests'), # get received list
    
    path('friend/remove/<int:friend_id>/', views.remove_friend, name='remove-friend'),
]

django_websocket_chatting/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from home.views import front_view

urlpatterns = [
    
    #path('', front_view , name='home'),
    path('', RedirectView.as_view(pattern_name='accounts:login'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('home/', include('home.urls')),
    path('docsumm/', include('docsumm.urls')),
    path('eventcalendar/', include('eventcalendar.urls', namespace='eventcalendar')),
    path('teams/', include('teams.urls')),
    path('ocr/', include('ocr.urls')),
    path('stt/', include('stt.urls')),
    
    # path('', RedirectView.as_view(pattern_name="chat:index"), name="root"),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

django_websocket_chatting/ocr/urls.py
# ocr/urls.py
from django.urls import path
from .views import OCRView

urlpatterns = [
    path('', OCRView.as_view(), name='ocr-home'),
]

django_websocket_chatting/config/templates/base.html
{% load django_bootstrap5 %}

<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>django channels</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% block extra-style %}{% endblock %}
</head>
<body>

<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-between py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-2 mb-md-0 text-dark text-decoration-none">
            장고 채널스
        </a>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li>
                <a href="/" class="nav-link px-2 link-secondary">
                    <img src="/static/images/logo.png" alt="AideaChat" style="height: 40px;">
                </a>
            </li>
        </ul>

        <div class="col-md-3 text-end">
            {% if not user.is_authenticated %}
                <a href="{% url 'accounts:login' %}" class="btn btn-outline-primary me-2">로그인</a>
                <a href="{% url 'accounts:signup' %}" class="btn btn-primary">회원가입</a>
            {% else %}
                <a href="{% url 'accounts:profile' %}" class="btn btn-outline-primary me-2">프로필</a>
                <a href="{% url 'accounts:logout' %}" class="btn btn-primary">로그아웃</a>
            {% endif %}
        </div>
    </header>

    {% bootstrap_messages %}

    {% block content %}{% endblock %}
</div>

{% block extra-script %}{% endblock %}

</body>
</html>