django_websocket_chatting/accounts/urls.py
from django.urls import path
from accounts import views


app_name = "accounts"

urlpatterns = [
    # user
    path('signup/', views.signup, name='signup'),
    path("login/", views.user_login, name="login"),
    path('logout/', views.logout_view, name='logout'),
    path("profile/", views.profile, name="profile"),
    
    # friend url
    path('friend-request/send/', views.SendFriendRequestView.as_view(), name='send-friend-request'),
    path('friend-request/accept/<int:pk>/', views.AcceptFriendRequestView.as_view(), name='accept-friend-request'),
    path('friend-request/reject/<int:pk>/', views.RejectFriendRequestView.as_view(), name='reject-friend-request'),
    
    path('friends/', views.ListFriendsView.as_view(), name='list_friends'),
    path('friend-management/', views.friend_management, name='friend_management'),
    path('friend-profile/', views.friend_profile, name='friend_profile'),   # Friend profile
    path('get-friends-list/', views.get_friends_list, name='get_friends_list'), # return Friend list
    path('friend-requests/received/', views.get_received_friend_requests, name='get_received_friend_requests'), # get received list
    
    path('friend/remove/<int:friend_id>/', views.remove_friend, name='remove-friend'),
]

django_websocket_chatting/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from home.views import front_view

urlpatterns = [
    
    #path('', front_view , name='home'),
    path('', RedirectView.as_view(pattern_name='accounts:login'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('home/', include('home.urls')),
    path('docsumm/', include('docsumm.urls')),
    path('eventcalendar/', include('eventcalendar.urls', namespace='eventcalendar')),
    path('teams/', include('teams.urls')),
    path('ocr/', include('ocr.urls')),
    path('stt/', include('stt.urls')),
    
    # path('', RedirectView.as_view(pattern_name="chat:index"), name="root"),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

django_websocket_chatting/ocr/urls.py
# ocr/urls.py
from django.urls import path
from .views import OCRView

urlpatterns = [
    path('', OCRView.as_view(), name='ocr-home'),
]

django_websocket_chatting/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from teams.models import Team
# Create your models here.


class CustomUser(AbstractUser):
    # 기존 필드인 username, password, email은 AbstractUser 모델에 이미 존재

    # 이름 필드 추가 
    name = models.CharField(max_length=100, verbose_name='이름')
    
    # '연락처' 필드 추가
    contact = models.CharField(max_length=20, verbose_name='연락처', null=True)

    # 프로필 사진 필드 추가
    profile_picture = models.ImageField(upload_to='profile_pictures/', null=True, blank=True, verbose_name='프로필 사진')
    
    # 다대다 관계 설정
    teams = models.ManyToManyField(Team, related_name='users', verbose_name='소속 팀')
    
    # 친구 목록 필드 추가 
    friends = models.ManyToManyField('self', blank=True)
    
    # 온라인 상태 필드
    is_online = models.BooleanField(default=False)

    
# 친구 요청 모델
class FriendRequest(models.Model):
    
    # 친구 요청을 보낸 사용자
    from_user = models.ForeignKey(CustomUser, related_name='sent_requests', on_delete=models.CASCADE)
    # 친구 요청을 받은 사용자
    to_user = models.ForeignKey(CustomUser, related_name='received_requests', on_delete=models.CASCADE)
    # 친구 요청이 생성된 시간
    timestamp = models.DateTimeField(auto_now_add=True)
    # 친구 요청이 수락되었는지 여부
    accepted = models.BooleanField(default=False)
    
    class Meta:
        unique_together = ('from_user', 'to_user')
    
    # 친구 요청을 수락하고, 요청을 보낸 사용자와 받은 사용자를 서로의 친구 목록에 추가
    def accept(self):
        self.accepted = True
        self.save()
        self.from_user.friends.add(self.to_user)
        self.to_user.friends.add(self.from_user)
        self.delete()  # 친구 요청을 수락한 후 해당 요청 삭제
        
    # 친구 요청을 거부하고 요청을 삭제
    def reject(self):
        self.delete()

django_websocket_chatting/accounts/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.hashers import make_password
from django.contrib.auth import login, logout, authenticate
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_POST, require_GET
from django.http import JsonResponse
from django.core.files.storage import default_storage
from django.views.decorators.http import require_http_methods

from rest_framework.decorators import api_view
from rest_framework import status, generics
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated

from .serializers import CustomUserSerializer, FriendRequestSerializer
from .models import CustomUser, FriendRequest

app_name = 'accounts'

@api_view(['GET', 'POST'])
def signup(request):
    if request.method == 'POST':
        serializer = CustomUserSerializer(data=request.data)
        if serializer.is_valid():
            password = serializer.validated_data.get('password')
            password2 = serializer.validated_data.get('password2')
            if password != password2:
                return render(request, 'accounts/signup.html', {
                    'error_message': "비밀번호가 일치하지 않습니다.",
                    'form': request.data,
                })
            
            # 비밀번호 해쉬화
            hashed_password = make_password(password)
            serializer.validated_data['password'] = hashed_password
            serializer.save()

            return redirect('accounts:login')  # 회원가입 성공 시 이동할 페이지
        return render(request, 'accounts/signup.html', {
            'errors': serializer.errors,
            'form': request.data,
        })
    return render(request, 'accounts/signup.html')


@csrf_protect
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return JsonResponse({'success': True}, status=200)
        else:
            return JsonResponse({'error_message': '로그인 정보가 올바르지 않습니다.'}, status=400)
    return render(request, 'accounts/login.html')

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return JsonResponse({'success': 'Logged out successfully'})
    return JsonResponse({'error': 'Invalid request'}, status=400)


@login_required
def profile(request):
    if request.method == 'POST' and request.FILES.get('profile_picture'):
        profile_picture = request.FILES['profile_picture']
        file_name = default_storage.save(f"profile_pictures/{profile_picture.name}", profile_picture)
        request.user.profile_picture = file_name
        request.user.save()
        return redirect('accounts:profile')

    return render(request, 'accounts/profile.html', {'user': request.user})


# 친구 요청을 보내는 엔드 포인트 
class SendFriendRequestView(generics.CreateAPIView):
    permission_classes = [IsAuthenticated]
    serializer_class = FriendRequestSerializer
    
    def create(self, request, *args, **kwargs):
        username =request.data.get('to_user')
        try:
            to_user = CustomUser.objects.get(username=username)
        except CustomUser.DoesNotExist:
            return Response({'detail': '등록된 유저가 조회되지 않습니다.'}, status=status.HTTP_400_BAD_REQUEST)
        
        to_user = get_object_or_404(CustomUser, username=request.data.get('to_user'))
        
        
        if FriendRequest.objects.filter(from_user=request.user, to_user=to_user).exists():
            return Response({'detail': '이미 친구요청을 보낸 사용자입니다.'}, status=status.HTTP_400_BAD_REQUEST)
        
        FriendRequest.objects.create(from_user=request.user, to_user=to_user)
        return Response({'detail': '친구요청을 보냈습니다!'}, status=status.HTTP_201_CREATED)

# 친구 요청을 수락하는 API 엔드포인트
class AcceptFriendRequestView(generics.UpdateAPIView):
    permission_classes = [IsAuthenticated]
    queryset = FriendRequest.objects.all()
    serializer_class = FriendRequestSerializer
    
    def update(self, request, *args, **kwargs):
        friend_request = get_object_or_404(FriendRequest, pk=kwargs['pk'])
        if friend_request.to_user != request.user:
            return Response({'detail': 'Not your friend request. '}, status=status.HTTP_400_BAD_REQUEST)
        friend_request.accept()
        return Response({'detail': 'Friend request accepted.'}, status=status.HTTP_200_OK)

# 친구 요청을 거부하는 API 엔드포인트
class RejectFriendRequestView(generics.DestroyAPIView):
    permission_calsses = [IsAuthenticated]
    
    def delete(self, request, *args, **kwargs ):
        friend_request = get_object_or_404(FriendRequest, pk=kwargs['pk'])
        if friend_request.to_user != request.user:
            return Response({'detail': 'Not your friend request.'}, status=status.HTTP_400_BAD_REQUEST)
        friend_request.reject()
        return Response({'detail': 'Friend request rejected.'}, status=status.HTTP_204_NO_CONTENT)

# 사용자의 친구 목록을 조회하는 API 엔드포인트=
class ListFriendsView(generics.ListAPIView):
    permission_classes = [IsAuthenticated]
    serializer_class = CustomUserSerializer
    
    def get_queryset(self):
        return self.request.user.friends.all()
    
# 친구 기능 html 템플릿 렌더링 뷰
@login_required
def friend_management(request):
    friends = request.user.friends.all()
    received_requests = request.user.received_requests.filter(accepted=False)
    sent_requests = request.user.sent_requests.filter(accepted=False)
    return render(request, 'friends/friend_management.html', {
        'friends': friends,
        'received_requests':received_requests,
        'sent_requests': sent_requests
    })
    

# 자신의 친구들 반환
@login_required
def get_friends_list(request):
    friends = request.user.friends.all()
    friends_data = [{'id': friend.id, 'username': friend.username, 'name': friend.name, 'is_online': friend.is_online,} for friend in friends]
    return JsonResponse({'friends': friends_data})

# 요청된 친구 요청들을 반환
@login_required
@require_http_methods(["GET"])
def get_received_friend_requests(request):
    received_requests = FriendRequest.objects.filter(to_user=request.user, accepted=False)
    for req in received_requests :
        print(req, "received")
    
    print(received_requests, "received")
    data = [
        {
            'id': req.id,
            'from_user': req.from_user.username,
            'timestamp': req.timestamp,
        } for req in received_requests
    ]
    return JsonResponse({'requests': data}, status=200)


# 친구 프로필 데이터 반환
@login_required
@require_GET
def friend_profile(request):
    friend_id = request.GET.get('id')
    friend = get_object_or_404(CustomUser, id=friend_id)
    print(friend.is_online)
    data = {
        'username': friend.username,
        'name' : friend.name,
        'email': friend.email,
        'profile_picture': friend.profile_picture.url if friend.profile_picture else '',
        'is_online' : friend.is_online,
        
    }
    return JsonResponse(data)

# 등록된 친구를 삭제하는 기능
@login_required
@require_http_methods(["DELETE"])
def remove_friend(request, friend_id):
    user = request.user
    friend = get_object_or_404(CustomUser, id=friend_id)

    if friend not in user.friends.all():
        return JsonResponse({'detail': 'Not your friend.'}, status=400)

    user.friends.remove(friend)
    friend.friends.remove(user)

    return JsonResponse({'detail': 'Friend removed successfully.'}, status=204)

django_websocket_chatting/accounts/templates/friends/friend_management.html
<!DOCTYPE html>
<html>
<head>
    <title>Friends List</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <style>
        .online .status-indicator {
            background-color: green;
        }
        .offline .status-indicator {
            background-color: red;
        }
        .status-indicator {
            display: inline-block;
            width: 10px;
            height: 10px;
            border-radius: 50%;
            margin-left: 5px;
        }
        #chat-button {
            display: none; /* 버튼을 기본적으로 숨깁니다 */
        }
        #loading-spinner {
            display: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Friends List</h2>
        <ul id="friend-list">
            {% for friend in friends %}
                <li data-id="{{ friend.id }}" class="{{ friend.is_online|yesno:'online,offline'}}"> 
                    <a href="#" class="friend-profile" data-id="{{ friend.id }}" data-toggle="modal" data-target="#profileModal">{{ friend.username }}</a>
                    <span class="status-indicator"></span>
                </li>
            {% endfor %}
        </ul>

        <h2>Received Friend Requests</h2>
        <ul>
            {% for request in received_requests %}
                <li>
                    {{ request.from_user.username }}
                    <button type="button" onclick="handleAccept({{ request.pk }})">Accept</button>
                    <button type="button" onclick="handleReject({{ request.pk }})">Reject</button>
                </li>
            {% endfor %}
        </ul>

        <h2>Send Friend Request</h2>
        <form id="send-friend-request-form" method="post" action="{% url 'accounts:send-friend-request' %}">
            {% csrf_token %}
            <div>친구추가할 친구의 아이디를 입력해주세요(별칭아님)</div>
            <label for="to_user">Username:</label>
            <input type="text" id="to_user" name="to_user" required>
            <button type="submit">Send Request</button>
        </form>
    </div>

    <!-- Profile Modal -->
    <div class="modal fade" id="profileModal" tabindex="-1" aria-labelledby="profileModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="profileModalLabel">Friend Profile</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="profile-info">
                    <!-- Profile info will be loaded here -->
                    <div id="loading-spinner" class="text-center">
                        <div class="spinner-border" role="status">
                            <span class="sr-only">Loading...</span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="chat-button">1:1 대화하기</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            // Websocket 연결 설정
            const ws = new WebSocket('ws://' + window.location.host + '/ws/status/');
            
            ws.onopen = function(event) {
                console.log("Websocket is open now.(friend status socket)");
            };
            
            ws.onmessage = function(event) {
                const data = JSON.parse(event.data);
                console.log("Message received:", data);  // 메시지 로그
                const userId = data.user_id;
                const isOnline = data.is_online;
                console.log("User ID:", userId, "Is Online:", isOnline);
                const friendElement = $(`#friend-list li[data-id='${userId}']`);
                if (friendElement.length > 0) {
                    if (isOnline) {
                        friendElement.addClass('online').removeClass('offline');
                    } else {
                        friendElement.addClass('offline').removeClass('online');
                    }
                }

            };
            
            ws.onerror = function(event) {
                console.error("WebSocket error observed:", event);
            };
            
            ws.onclose = function(event) {
                console.log("WebSocket is closed now.");
            };
            
            // friend profile 정의
            $('.friend-profile').click(function() {
                const friendId = $(this).data('id');
                $('#chat-button').hide(); // 프로필 정보가 로드되기 전까지 숨깁니다.
                $('#loading-spinner').show(); // 로딩 스피너를 표시합니다.
                $.ajax({
                    url: `{% url 'accounts:friend_profile' %}`,
                    method: 'GET',
                    data: {id: friendId},
                    success: function(data) {
                        const profilePicturehtml = data.profile_picture ? `<img src="${data.profile_picture}" alt="Profile Picture" width="100" height="100">` : '등록된 프로필 이미지 없음';

                        $('#profile-info').html(
                            `<strong>Username:</strong> ${data.username}<br>
                            <strong>Name:</strong> ${data.name}<br>
                            <strong>Email:</strong> ${data.email}<br>
                            <strong>Profile image:</strong> ${profilePicturehtml}`
                        );
                        
                        $('#loading-spinner').hide(); // 로딩 스피너를 숨깁니다.
                        $('#chat-button').data('username', data.username).data('friendId', friendId).show(); // 프로필 정보가 로드된 후 버튼을 표시합니다.
                    }
                });
            });

            $('#chat-button').click(function(){
                const friendUsername = $(this).data('username');
                window.location.href = `/chat/private_chat/${friendUsername}/`;
            });

            $('#send-friend-request-form').submit(function(event) {
                event.preventDefault();

                const formData = $(this).serialize();

                $.ajax({
                    url: $(this).attr('action'),
                    method: 'POST',
                    data: formData,
                    success: function(data) {
                        toastr.success(data.detail);
                    },
                    error: function(xhr) {
                        const errorDetail = xhr.responseJSON.detail;
                        toastr.error(errorDetail);
                    }
                });
            });
        });

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        const csrftoken = getCookie('csrftoken');

        function handleAccept(requestId) {
            fetch(`/accounts/friend-request/accept/${requestId}/`, {
                method: 'PUT',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken,
                }
            })
            .then(response => response.json())
            .then(data => {
                toastr.success(data.detail);
                location.reload();  // 페이지를 새로고침하여 변경 사항을 반영
            })
            .catch(error => {
                const errorDetail = error.responseJSON.detail;
                toastr.error(errorDetail);
            });
        }

        function handleReject(requestId) {
            fetch(`/accounts/friend-request/reject/${requestId}/`, {
                method: 'DELETE',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken,
                }
            })
            .then(response => {
                if (response.status === 204) {
                    toastr.success('Friend request rejected.');
                    location.reload();  // 페이지를 새로고침하여 변경 사항을 반영
                } else {
                    return response.json();
                }
            })
            .then(data => {
                if (data && data.detail) {
                    toastr.error(data.detail);
                }
            })
            .catch(error => {
                const errorDetail = error.responseJSON.detail;
                toastr.error(errorDetail);
            });
        }
    </script>
</body>
</html>