django_websocket_chatting/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from home.views import front_view

urlpatterns = [
    
    #path('', front_view , name='home'),
    path('', RedirectView.as_view(pattern_name='accounts:login'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('home/', include('home.urls')),
    path('docsumm/', include('docsumm.urls')),
    path('eventcalendar/', include('eventcalendar.urls', namespace='eventcalendar')),
    path('teams/', include('teams.urls')),
    path('ocr/', include('ocr.urls')),
    path('stt/', include('stt.urls')),
    
    # path('', RedirectView.as_view(pattern_name="chat:index"), name="root"),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

django_websocket_chatting/ocr/urls.py
# ocr/urls.py
from django.urls import path
from .views import OCRView

urlpatterns = [
    path('', OCRView.as_view(), name='ocr-home'),
]

django_websocket_chatting/teams/urls.py
from django.urls import path
from teams import views

app_name = "teams"

urlpatterns = [
    # group
    path('teams_list/', views.teams_list, name='teams_list'),
    path('teams_create/', views.teams_create, name='teams_create'),
    path('delete_team/<int:team_id>/', views.delete_team, name='delete_team'),
    
    # invate
    path('invite_user/<int:team_id>/', views.invite_user, name='invite_user'),
    path('accept_invitation/<int:invitation_id>/', views.accept_invitation, name='accept_invitation'),
    path('reject_invitation/<int:invitation_id>/', views.reject_invitation, name='reject_invitation'),
    path('leave_team/<int:team_id>/', views.leave_team, name='leave_team'),
    path('get_invitations/', views.get_invitations, name='get_invitations'),
    path('get_team_members/', views.get_team_members, name='get_team_members'),
]

django_websocket_chatting/teams/models.py
from django.conf import settings
from django.db import models

#주석
class Team(models.Model):
    name = models.CharField(max_length=100, verbose_name='팀 이름')
    
    description = models.TextField(null=True, blank=True, verbose_name='팀 설명')
    
    team_image = models.ImageField(upload_to='team_image/', null=True, blank=True, verbose_name='팀 사진')
    
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='owned_teams', verbose_name='팀 소유자', null=True, blank=True)
    
    @property
    def members(self):
        return self.users.all()

    def __str__(self):
        return self.name

class TeamInvitation(models.Model):
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='sent_team_invitations', on_delete=models.CASCADE)
    to_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='received_team_invitations', on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    accepted = models.BooleanField(default=False)

    class Meta:
        unique_together = ('from_user', 'to_user', 'team')

    def accept(self):
        self.accepted = True
        self.save()
        self.team.users.add(self.to_user)
        self.delete()

    def reject(self):
        self.delete()

django_websocket_chatting/teams/views.py
import json
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST, require_GET
from django.http import JsonResponse
from django.shortcuts import get_object_or_404

from rest_framework.decorators import api_view
from rest_framework import serializers, status
from rest_framework.response import Response

from accounts.models import CustomUser

from .serializers import TeamSerializer
from .models import Team, TeamInvitation


@login_required
@api_view(['GET'])
def teams_list(request):
    user = request.user
    teams = user.teams.all()  # 현재 유저가 속한 팀 목록
    return render(request, 'team/teams_list.html', {'teams': teams})


@login_required
@api_view(['GET', 'POST'])
def teams_create(request):
    
    if request.method == 'GET':
        teams = Team.objects.all()
        form = TeamSerializer()
        return render(request, 'team/teams_create.html', {'teams': teams, 'form': form})
    
    elif request.method == 'POST':
        serializer = TeamSerializer(data=request.data)
        if serializer.is_valid():
            team = serializer.save(owner=request.user)
            request.user.teams.add(team)
            return redirect('teams:teams_list')
        
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    

@login_required
@require_http_methods(["DELETE"])
def delete_team(request, team_id):
    team = get_object_or_404(Team, id=team_id)
    if team.owner != request.user:
        return JsonResponse({'status': 'fail', 'error': '팀의 관리자만 팀을 삭제할 수 있습니다.'}, status=403)
    try:
        team.delete()
        return JsonResponse({'status': 'success'})
    except Exception as e:
        return JsonResponse({'status': 'fail', 'error': str(e)}, status=400)


###  팀 초대 관련 부분 

@login_required
@require_POST
def invite_user(request, team_id):
    team = get_object_or_404(Team, id=team_id)
    if team.owner != request.user:
        return JsonResponse({'error': '권한이 없습니다.'}, status=403)

    data = json.loads(request.body)
    user_id = data.get('user_id')
    
    try:
        user = CustomUser.objects.get(username=user_id)
    except CustomUser.DoesNotExist:
        return JsonResponse({'error': '사용자를 찾을 수 없습니다.'}, status=404)

    if user in team.users.all():
        return JsonResponse({'error': '사용자는 이미 팀의 멤버입니다.'}, status=400)

    if TeamInvitation.objects.filter(to_user=user, team=team).exists():
        return JsonResponse({'error': '이미 초대 요청이 있습니다.'}, status=400)

    TeamInvitation.objects.create(from_user=request.user, to_user=user, team=team)
    return JsonResponse({'success': '초대 요청이 발송되었습니다.'}, status=200)

# 팀 초대 목록
@login_required
@require_GET
def get_invitations(request):
    invitations = TeamInvitation.objects.filter(to_user=request.user, accepted=False)
    invitation_data = [{'id': inv.id, 'team_name': inv.team.name} for inv in invitations]
    return JsonResponse({'invitations': invitation_data})

@login_required
@require_http_methods(["POST"])
def accept_invitation(request, invitation_id):
    invitation = get_object_or_404(TeamInvitation, id=invitation_id, to_user=request.user)
    invitation.accept()
    return JsonResponse({'success': '초대 요청을 수락했습니다.'}, status=200)


@login_required
@require_http_methods(["POST", "DELETE"])
def reject_invitation(request, invitation_id):
    invitation = get_object_or_404(TeamInvitation, id=invitation_id, to_user=request.user)
    invitation.reject()
    return JsonResponse({'success': '초대 요청을 거절했습니다.'}, status=200)


def leave_team(request, team_id):
    team = get_object_or_404(Team, id=team_id)
    if request.user not in team.users.all():
        return JsonResponse({'error': '팀의 멤버가 아닙니다.'}, status=400)

    if team.owner == request.user:
        return JsonResponse({'error': '팀 소유자는 팀을 탈퇴할 수 없습니다.'}, status=400)

    team.users.remove(request.user)
    return JsonResponse({'success': '팀에서 탈퇴했습니다.'}, status=200)

@login_required
def get_team_members(request):
    team_id = request.GET.get('team_id')
    team = get_object_or_404(Team, id=team_id)
    
    team_members = team.members.all()
    members_data = []
    for member in team_members:
        members_data.append({
            'id': member.id,
            'name' : member.name,
            'username': member.username,
            'is_online': member.is_online  # 'is_online'은 User 모델에 정의된 속성이라고 가정합니다
        })

    return JsonResponse({'team_members': members_data})

django_websocket_chatting/teams/templates/team/teams_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/3c8aeb941b.js" crossorigin="anonymous"></script>
    <title>Create a New Team</title>
    <style>
        body { 
            font-family: 'Roboto', sans-serif; 
            background-color: #B2DFDB;/* 연한 민트색 배경 */
            color: #00796b; /* 어두운 민트색 텍스트 */
            text-align: center;
            margin: 0;
            padding: 0;
        }
        .container { 
            max-width: 500px; 
            margin: 50px auto; 
            padding: 20px; 
            background-color: #FFFFFF; /* 흰색 배경 */
            border-radius: 10px; 
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            margin-top: 150px;
        }
        h2 { 
            margin-bottom: 20px; 
            color: #00796B; /* 진한 민트색 텍스트 */
            font-size: 24px;
        }
        form { 
            background-color: #E0F7FA; /* 연한 민트색 배경 */
            border-radius: 10px; 
            padding: 20px; 
            text-align: left; 
        }
        label { 
            font-weight: bold; 
            margin-bottom: 5px;
            display: inline-block;
        }
        input[type="text"], textarea, input[type="file"] {
            width: 100%; 
            padding: 10px; 
            margin-bottom: 15px; 
            border: 1px solid #ddd; 
            border-radius: 5px; 
            box-sizing: border-box; 
            font-size: 16px;
        }
        button[type="submit"] {
            background-color: #004D40; /* 어두운 민트색 배경 */
            color: white; /* 하얀색 텍스트 */
            border: none; 
            padding: 15px 20px; 
            border-radius: 5px; 
            cursor: pointer; 
            font-size: 16px;
            width: 100%;
            transition: background-color 0.3s, color 0.3s;
        }
        button[type="submit"]:hover {
            background-color: #00796B; /* 진한 민트색 배경 */
        }
        #imagePreview img {
            max-width: 100%; 
            height: auto; 
            border-radius: 5px; 
            margin-top: 10px;
        }
        .fa-plus {
            margin: 10px;
        }
        .error-message {
            color: red;
            font-size: 14px;
            margin-top: 5px;
            margin-bottom: 15px;
        }
    </style>
</head>
<body>
    <div class="container">
        
        <div><i class="fa-solid fa-users-viewfinder fa-5x"></i></div>
        <h2>새로운 팀 생성하기</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <label for="id_team_image"><i class="fa-solid fa-clover"></i> - 팀 프로필 이미지 :</label><br>
                <input type="file" name="team_image" id="id_team_image" onchange="previewImage(event)">
                <div id="errorMessage" class="error-message"></div>
                <div id="imagePreview"></div>
            </div>

            <script>
                function previewImage(event) {
                    var file = event.target.files[0];
                    var fileType = file.type;
                    var validImageTypes = ["image/gif", "image/jpeg", "image/png", "image/jpg"];

                    if (!validImageTypes.includes(fileType)) {
                        var errorMessage = document.getElementById('errorMessage');
                        errorMessage.innerHTML = "이미지 파일이 아닙니다.<br>.gif / .jpeg / .png / .jpg 파일만 프로필 선택 가능";
                        document.getElementById('imagePreview').innerHTML = '';
                        return;
                    } else {
                        document.getElementById('errorMessage').textContent = '';
                    }

                    var reader = new FileReader();
                    reader.onload = function(){
                        var output = document.getElementById('imagePreview');
                        output.innerHTML = '<img src="' + reader.result + '">';
                    }
                    reader.readAsDataURL(file);
                }
            </script>

            <div>
                <label for="id_name"><i class="fa-solid fa-clover"></i> -  팀 이름:</label><br>
                <input type="text" name="name" required id="id_name">
            </div>
            <div>
                <label for="id_description"><i class="fa-solid fa-clover"></i> - 팀 설명 :</label><br>
                <textarea name="description" cols="40" rows="5" id="id_description"></textarea>
            </div>

            <button type="submit">팀 생성</button>
        </form>
    </div>
</body>
</html>