django_websocket_chatting/accounts/urls.py
from django.urls import path
from accounts import views


app_name = "accounts"

urlpatterns = [
    # user
    path('signup/', views.signup, name='signup'),
    path("login/", views.user_login, name="login"),
    path('logout/', views.logout_view, name='logout'),
    path("profile/", views.profile, name="profile"),
    
    # friend url
    path('friend-request/send/', views.SendFriendRequestView.as_view(), name='send-friend-request'),
    path('friend-request/accept/<int:pk>/', views.AcceptFriendRequestView.as_view(), name='accept-friend-request'),
    path('friend-request/reject/<int:pk>/', views.RejectFriendRequestView.as_view(), name='reject-friend-request'),
    
    path('friends/', views.ListFriendsView.as_view(), name='list_friends'),
    path('friend-management/', views.friend_management, name='friend_management'),
    path('friend-profile/', views.friend_profile, name='friend_profile'),   # Friend profile
    path('get-friends-list/', views.get_friends_list, name='get_friends_list'), # return Friend list
    path('friend-requests/received/', views.get_received_friend_requests, name='get_received_friend_requests'), # get received list
    
    path('friend/remove/<int:friend_id>/', views.remove_friend, name='remove-friend'),
]

django_websocket_chatting/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from home.views import front_view

urlpatterns = [
    
    #path('', front_view , name='home'),
    path('', RedirectView.as_view(pattern_name='accounts:login'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('home/', include('home.urls')),
    path('docsumm/', include('docsumm.urls')),
    path('eventcalendar/', include('eventcalendar.urls', namespace='eventcalendar')),
    path('teams/', include('teams.urls')),
    path('ocr/', include('ocr.urls')),
    path('stt/', include('stt.urls')),
    
    # path('', RedirectView.as_view(pattern_name="chat:index"), name="root"),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

django_websocket_chatting/ocr/urls.py
# ocr/urls.py
from django.urls import path
from .views import OCRView

urlpatterns = [
    path('', OCRView.as_view(), name='ocr-home'),
]

django_websocket_chatting/teams/urls.py
from django.urls import path
from teams import views

app_name = "teams"

urlpatterns = [
    # group
    path('teams_list/', views.teams_list, name='teams_list'),
    path('teams_create/', views.teams_create, name='teams_create'),
    path('delete_team/<int:team_id>/', views.delete_team, name='delete_team'),
    
    # invate
    path('invite_user/<int:team_id>/', views.invite_user, name='invite_user'),
    path('accept_invitation/<int:invitation_id>/', views.accept_invitation, name='accept_invitation'),
    path('reject_invitation/<int:invitation_id>/', views.reject_invitation, name='reject_invitation'),
    path('leave_team/<int:team_id>/', views.leave_team, name='leave_team'),
    path('get_invitations/', views.get_invitations, name='get_invitations'),
    path('get_team_members/', views.get_team_members, name='get_team_members'),
]

django_websocket_chatting/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from teams.models import Team
# Create your models here.


class CustomUser(AbstractUser):
    # 기존 필드인 username, password, email은 AbstractUser 모델에 이미 존재

    # 이름 필드 추가 
    name = models.CharField(max_length=100, verbose_name='이름')
    
    # '연락처' 필드 추가
    contact = models.CharField(max_length=20, verbose_name='연락처', null=True)

    # 프로필 사진 필드 추가
    profile_picture = models.ImageField(upload_to='profile_pictures/', null=True, blank=True, verbose_name='프로필 사진')
    
    # 다대다 관계 설정
    teams = models.ManyToManyField(Team, related_name='users', verbose_name='소속 팀')
    
    # 친구 목록 필드 추가 
    friends = models.ManyToManyField('self', blank=True)
    
    # 온라인 상태 필드
    is_online = models.BooleanField(default=False)

    
# 친구 요청 모델
class FriendRequest(models.Model):
    
    # 친구 요청을 보낸 사용자
    from_user = models.ForeignKey(CustomUser, related_name='sent_requests', on_delete=models.CASCADE)
    # 친구 요청을 받은 사용자
    to_user = models.ForeignKey(CustomUser, related_name='received_requests', on_delete=models.CASCADE)
    # 친구 요청이 생성된 시간
    timestamp = models.DateTimeField(auto_now_add=True)
    # 친구 요청이 수락되었는지 여부
    accepted = models.BooleanField(default=False)
    
    class Meta:
        unique_together = ('from_user', 'to_user')
    
    # 친구 요청을 수락하고, 요청을 보낸 사용자와 받은 사용자를 서로의 친구 목록에 추가
    def accept(self):
        self.accepted = True
        self.save()
        self.from_user.friends.add(self.to_user)
        self.to_user.friends.add(self.from_user)
        self.delete()  # 친구 요청을 수락한 후 해당 요청 삭제
        
    # 친구 요청을 거부하고 요청을 삭제
    def reject(self):
        self.delete()

django_websocket_chatting/accounts/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.hashers import make_password
from django.contrib.auth import login, logout, authenticate
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_POST, require_GET
from django.http import JsonResponse
from django.core.files.storage import default_storage
from django.views.decorators.http import require_http_methods

from rest_framework.decorators import api_view
from rest_framework import status, generics
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated

from .serializers import CustomUserSerializer, FriendRequestSerializer
from .models import CustomUser, FriendRequest

app_name = 'accounts'

@api_view(['GET', 'POST'])
def signup(request):
    if request.method == 'POST':
        serializer = CustomUserSerializer(data=request.data)
        if serializer.is_valid():
            password = serializer.validated_data.get('password')
            password2 = serializer.validated_data.get('password2')
            if password != password2:
                return render(request, 'accounts/signup.html', {
                    'error_message': "비밀번호가 일치하지 않습니다.",
                    'form': request.data,
                })
            
            # 비밀번호 해쉬화
            hashed_password = make_password(password)
            serializer.validated_data['password'] = hashed_password
            serializer.save()

            return redirect('accounts:login')  # 회원가입 성공 시 이동할 페이지
        return render(request, 'accounts/signup.html', {
            'errors': serializer.errors,
            'form': request.data,
        })
    return render(request, 'accounts/signup.html')


@csrf_protect
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return JsonResponse({'success': True}, status=200)
        else:
            return JsonResponse({'error_message': '로그인 정보가 올바르지 않습니다.'}, status=400)
    return render(request, 'accounts/login.html')

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return JsonResponse({'success': 'Logged out successfully'})
    return JsonResponse({'error': 'Invalid request'}, status=400)


@login_required
def profile(request):
    if request.method == 'POST' and request.FILES.get('profile_picture'):
        profile_picture = request.FILES['profile_picture']
        file_name = default_storage.save(f"profile_pictures/{profile_picture.name}", profile_picture)
        request.user.profile_picture = file_name
        request.user.save()
        return redirect('accounts:profile')

    return render(request, 'accounts/profile.html', {'user': request.user})


# 친구 요청을 보내는 엔드 포인트 
class SendFriendRequestView(generics.CreateAPIView):
    permission_classes = [IsAuthenticated]
    serializer_class = FriendRequestSerializer
    
    def create(self, request, *args, **kwargs):
        username =request.data.get('to_user')
        try:
            to_user = CustomUser.objects.get(username=username)
        except CustomUser.DoesNotExist:
            return Response({'detail': '등록된 유저가 조회되지 않습니다.'}, status=status.HTTP_400_BAD_REQUEST)
        
        to_user = get_object_or_404(CustomUser, username=request.data.get('to_user'))
        
        
        if FriendRequest.objects.filter(from_user=request.user, to_user=to_user).exists():
            return Response({'detail': '이미 친구요청을 보낸 사용자입니다.'}, status=status.HTTP_400_BAD_REQUEST)
        
        FriendRequest.objects.create(from_user=request.user, to_user=to_user)
        return Response({'detail': '친구요청을 보냈습니다!'}, status=status.HTTP_201_CREATED)

# 친구 요청을 수락하는 API 엔드포인트
class AcceptFriendRequestView(generics.UpdateAPIView):
    permission_classes = [IsAuthenticated]
    queryset = FriendRequest.objects.all()
    serializer_class = FriendRequestSerializer
    
    def update(self, request, *args, **kwargs):
        friend_request = get_object_or_404(FriendRequest, pk=kwargs['pk'])
        if friend_request.to_user != request.user:
            return Response({'detail': 'Not your friend request. '}, status=status.HTTP_400_BAD_REQUEST)
        friend_request.accept()
        return Response({'detail': 'Friend request accepted.'}, status=status.HTTP_200_OK)

# 친구 요청을 거부하는 API 엔드포인트
class RejectFriendRequestView(generics.DestroyAPIView):
    permission_calsses = [IsAuthenticated]
    
    def delete(self, request, *args, **kwargs ):
        friend_request = get_object_or_404(FriendRequest, pk=kwargs['pk'])
        if friend_request.to_user != request.user:
            return Response({'detail': 'Not your friend request.'}, status=status.HTTP_400_BAD_REQUEST)
        friend_request.reject()
        return Response({'detail': 'Friend request rejected.'}, status=status.HTTP_204_NO_CONTENT)

# 사용자의 친구 목록을 조회하는 API 엔드포인트=
class ListFriendsView(generics.ListAPIView):
    permission_classes = [IsAuthenticated]
    serializer_class = CustomUserSerializer
    
    def get_queryset(self):
        return self.request.user.friends.all()
    
# 친구 기능 html 템플릿 렌더링 뷰
@login_required
def friend_management(request):
    friends = request.user.friends.all()
    received_requests = request.user.received_requests.filter(accepted=False)
    sent_requests = request.user.sent_requests.filter(accepted=False)
    return render(request, 'friends/friend_management.html', {
        'friends': friends,
        'received_requests':received_requests,
        'sent_requests': sent_requests
    })
    

# 자신의 친구들 반환
@login_required
def get_friends_list(request):
    friends = request.user.friends.all()
    friends_data = [{'id': friend.id, 'username': friend.username, 'name': friend.name, 'is_online': friend.is_online,} for friend in friends]
    return JsonResponse({'friends': friends_data})

# 요청된 친구 요청들을 반환
@login_required
@require_http_methods(["GET"])
def get_received_friend_requests(request):
    received_requests = FriendRequest.objects.filter(to_user=request.user, accepted=False)
    for req in received_requests :
        print(req, "received")
    
    print(received_requests, "received")
    data = [
        {
            'id': req.id,
            'from_user': req.from_user.username,
            'timestamp': req.timestamp,
        } for req in received_requests
    ]
    return JsonResponse({'requests': data}, status=200)


# 친구 프로필 데이터 반환
@login_required
@require_GET
def friend_profile(request):
    friend_id = request.GET.get('id')
    friend = get_object_or_404(CustomUser, id=friend_id)
    print(friend.is_online)
    data = {
        'username': friend.username,
        'name' : friend.name,
        'email': friend.email,
        'profile_picture': friend.profile_picture.url if friend.profile_picture else '',
        'is_online' : friend.is_online,
        
    }
    return JsonResponse(data)

# 등록된 친구를 삭제하는 기능
@login_required
@require_http_methods(["DELETE"])
def remove_friend(request, friend_id):
    user = request.user
    friend = get_object_or_404(CustomUser, id=friend_id)

    if friend not in user.friends.all():
        return JsonResponse({'detail': 'Not your friend.'}, status=400)

    user.friends.remove(friend)
    friend.friends.remove(user)

    return JsonResponse({'detail': 'Friend removed successfully.'}, status=204)

django_websocket_chatting/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Site{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

django_websocket_chatting/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/dab690a483.js" crossorigin="anonymous"></script>
    <title>AideaChat</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            font-family: Arial, sans-serif;
            background: linear-gradient(135deg, rgb(28, 207, 183), #c2f1f1);
            padding: 0;
            overflow: hidden;
        }
        .container {
            text-align: center;
            background: white;
            padding: 2rem;
            border-radius: 1rem;
            box-shadow: 0 0 1rem rgba(0, 0, 0, 0.1);
            width: 90%;
            max-width: 400px;
        }
        .container h1 {
            font-size: 2rem;
            color: #333;
        }
        .message {
            font-size: 1.2rem;
            color: #666;
            margin-top: 1rem;
            opacity: 1;
            transition: opacity 2s;
        }
        .start-button, .login-button, .signup-button {
            display: none;
            margin-top: 2rem;
            padding: 0.75rem 1.5rem;
            border: none;
            border-radius: 0.5rem;
            background: #026d68;
            color: white;
            font-size: 1rem;
            cursor: pointer;
            width: 115px;
        }
        .start-button:hover, .login-button:hover, .signup-button:hover {
            background: #81f0ea;
        }
        .modal {
            display: none;
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            height: 50%;
            background: white;
            border-top-left-radius: 1rem;
            border-top-right-radius: 1rem;
            box-shadow: 0 -1rem 1rem rgba(0, 0, 0, 0.1);
            transform: translateY(100%);
            transition: transform 0.3s ease-in-out;
            background-color: #9fd1ca;
        }
        .modal.open {
            display: block;
            transform: translateY(0);
        }
        .modal-content {
            padding: 2rem;
        }
        .modal-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 1px solid #eee;
            padding-bottom: 1rem;
            margin-bottom: 1rem;
        }
        .modal-header h2 {
            margin: 0;
            font-size: 1.5rem;
            color: #333;
        }
        .close-button {
            background: none;
            border: none;
            font-size: 1.5rem;
            cursor: pointer;
        }
        .input-group {
            margin-bottom: 0.7rem;
            text-align: left;
            width: 100%;
        }
        .input-group label {
            display: block;
            margin-bottom: 0.25rem;
            color: #666;
            font-size: 1rem;
        }
        .input-group input {
            width: 100%;
            padding: 0.5rem;
            border: 1px solid #ccc;
            border-radius: 0.5rem;
            font-size: 1rem;
        }
        .login-submit {
            width: 100%;
            padding: 0.75rem;
            border: none;
            border-radius: 0.5rem;
            background: #026d68;
            color: white;
            font-size: 1.25rem;
            cursor: pointer;
            margin-top: 1rem;
            margin-bottom: 1rem; /* 추가 */
        }
        .login-submit:hover {
            background: white;
            color: #026d68;
        }
        .fa-comment-dots {
            color: rgb(15, 163, 143);
        }
        .container h1 {
            color: rgb(15, 163, 143);
        }
        .modal-header h2 {
            margin-right: -500;
        }
        .fa-comments {
            color: rgb(250, 255, 254);
        }
        .parent {
            margin-left: -20px;
        }
        #error-message {
            color: red;
            height: 1.2rem; /* Adjust this height as needed */
            margin-top: 0.5rem; /* Adjust this margin as needed */
            text-align: center; /* Center the error message */
        }
    </style>
</head>
<body>

    <div class="parent">
        <div class="container">
            <div class="icon"><i class="fas fa-solid fa-comment-dots fa-7x"></i></div>
            <h1>Aidea Chat</h1>
            <div class="message" id="welcome-message">C H A T A P P & M E S S A G E</div>
            <button class="start-button" id="start-button">시작하기</button>
            <button class="login-button" id="login-button">로그인</button>
            <button class="signup-button" id="signup-button">회원가입</button>
        </div>
    </div>

    <div class="modal" id="login-modal">
        <div class="modal-content">
            <div class="modal-header">
                <h2></h2>
                <i class="fas fa-regular fa-comments fa-5x"></i>
                <button class="close-button" id="close-button">&times;</button>
            </div>
            <form id="login-form" method="post">
                {% csrf_token %}
                <div class="input-group">
                    <label for="username">아이디:</label>
                    <input type="text" id="username" name="username" required>
                </div>
                <div class="input-group">
                    <label for="password">비밀번호:</label>
                    <input type="password" id="password" name="password" required>
                </div>
                <p id="error-message" style="display: none;"></p>
                <button type="submit" class="login-submit">로그인</button>
            </form>
        </div>
    </div>

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const message = document.getElementById("welcome-message");
            const startButton = document.getElementById("start-button");
            const loginButton = document.getElementById("login-button");
            const signupButton = document.getElementById("signup-button");
            const loginModal = document.getElementById("login-modal");
            const closeButton = document.getElementById("close-button");
            const loginForm = document.getElementById("login-form");
            const errorMessage = document.getElementById("error-message");

            setTimeout(() => {
                message.style.opacity = 0;
                setTimeout(() => {
                    message.style.display = "none";
                    startButton.style.display = "inline-block";
                }, 2000); // wait for the opacity transition to complete
            }, 3000);

            startButton.addEventListener("click", function() {
                startButton.style.display = "none";
                loginButton.style.display = "inline-block";
                signupButton.style.display = "inline-block";
            });

            loginButton.addEventListener("click", function() {
                loginModal.classList.add("open");
            });

            closeButton.addEventListener("click", function() {
                loginModal.classList.remove("open");
            });

            signupButton.addEventListener("click", function() {
                window.location.href = "{% url 'accounts:signup' %}";
            });

            loginForm.addEventListener("submit", function(event) {
                event.preventDefault();
                const formData = new FormData(loginForm);

                fetch("{% url 'accounts:login' %}", {
                    method: "POST",
                    body: formData,
                    headers: {
                        "X-CSRFToken": formData.get("csrfmiddlewaretoken")
                    }
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        window.location.href = "{% url 'teams:teams_list' %}";
                    } else if (data.error_message) {
                        errorMessage.textContent = data.error_message;
                        errorMessage.style.display = "block";
                    }
                })
                .catch(error => {
                    console.error("Error:", error);
                });
            });
        });
    </script>
</body>
</html>

django_websocket_chatting/accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/dab690a483.js" crossorigin="anonymous"></script>
    <title>회원가입</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            font-family: Arial, sans-serif;
            background: #F4F6F9;
            padding: 0;
            background-color: #9fd1ca;
        }
        .signup-container {
            background: white;
            padding: 2rem;
            border-radius: 1rem;
            box-shadow: 0 0 1rem rgba(0, 0, 0, 0.1);
            width: 90%;
            max-width: 400px;
            overflow-y: auto;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        .signup-container h2 {
            margin-bottom: 1rem;
            color: #333;
            font-size: 1.5rem;
        }
        .input-group {
            margin-bottom: 1rem;
            text-align: left;
            width: 100%;
            position: relative;
        }
        .input-group label {
            display: block;
            margin-bottom: 0.5rem;
            color: #666;
            font-size: 1rem;
        }
        .input-group input, .input-group textarea, .input-group input[type="file"] {
            width: 100%;
            padding: 0.75rem;
            border: 1px solid #ccc;
            border-radius: 0.5rem;
            font-size: 1rem;
            box-sizing: border-box;
        }
        .error-message {
            color: red;
            font-size: 14px;
            margin-top: 5px;
            margin-bottom: 15px;
        }
        .signup-button {
            width: 100%;
            padding: 0.75rem;
            border: none;
            border-radius: 0.5rem;
            background: #357C76;
            color: white;
            font-size: 1.25rem;
            cursor: pointer;
            text-decoration: none;
            display: inline-block;
            margin-top: 1rem;
        }
        .signup-button:hover {
            background: #27ae60;
        }
        .head {
            color: rgb(36, 120, 109);
            text-align: center;
        }
        #imagePreview img {
            max-width: 100%;
            height: auto;
            border-radius: 5px;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <div class="signup-container">
        <div class="head">
            <h2>Welcome to</h2><h1>Aldea CHAT</h1>
        </div>
        <form method="post" enctype="multipart/form-data" action="{% url 'accounts:signup' %}">
            {% csrf_token %}
            <div class="input-group">
                <label for="id_username">🍀 - 아이디</label>
                <input type="text" id="id_username" name="username" required value="{{ form.username }}">
            </div>
            <div class="input-group">
                <label for="id_password">🍀 - 비밀번호</label>
                <input type="password" id="id_password" name="password" required>
            </div>
            <div class="input-group">
                <label for="id_password2">🍀 - 비밀번호 확인</label>
                <input type="password" id="id_password2" name="password2" required>
                {% if error_message %}
                    <div class="error-message">{{ error_message }}</div>
                {% endif %}
            </div>
            <div class="input-group">
                <label for="id_name">🍀 - 이름</label>
                <input type="text" id="id_name" name="name" required value="{{ form.name }}">
            </div>
            <div class="input-group">
                <label for="id_contact">🍀 - 전화번호</label>
                <input type="text" id="id_contact" name="contact" required placeholder="000-0000-0000" value="{{ form.contact }}">
            </div>
            <div class="input-group">
                <label for="id_profile_picture">🍀 - 프로필 사진</label>
                <input type="file" id="id_profile_picture" name="profile_picture" onchange="previewImage(event)">
                <div id="errorMessage" class="error-message"></div>
                <div id="imagePreview"></div>
            </div>
            <button type="submit" class="signup-button">회원가입</button>
        </form>
    </div>

    <script>
        function previewImage(event) {
            var file = event.target.files[0];
            var fileType = file.type;
            var validImageTypes = ["image/gif", "image/jpeg", "image/png", "image/jpg"];

            if (!validImageTypes.includes(fileType)) {
                var errorMessage = document.getElementById('errorMessage');
                errorMessage.innerHTML = "이미지 파일이 아닙니다.<br>.gif / .jpeg / .png / .jpg 파일만 선택 가능";
                document.getElementById('imagePreview').innerHTML = '';
                return;
            } else {
                document.getElementById('errorMessage').textContent = '';
            }

            var reader = new FileReader();
            reader.onload = function(){
                var output = document.getElementById('imagePreview');
                output.innerHTML = '<img src="' + reader.result + '">';
            }
            reader.readAsDataURL(file);
        }
    </script>
</body>
</html>